### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by deltakosh** [MatthieuMEZIL/waqs#21]
You should define what waqs means

**Comment by MatthieuMEZIL** [comment]
I think WAQS (WCF Async Queryable Services) was a good name at the beginning when WAQS was "just" a way to querying asynchronously from the client using WCF. 
But now, even if I can replace WCF by Web, it is not really relevant IMO

That's why I renamed everything which was WCFAsyncQueryableServices in my source code to just use WAQS.

That's also why I did not define what it means because I think it could be very reductive for readers.
